version: '3.9'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - 'mongo'

  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

volumes:
  mongo:
